### ISSUE TITLE
Meta tags

### ISSUE THREAD

**Issue by carvalho2707** [LolStatsOrganization/LOLStats#75]
- [ ] meta description
- [ ] meta og description
- [ ] meta keywords
- [ ] twitter meta tags
- [ ] google+ meta tags
- [ ] meta tag share pages

**Comment by carvalho2707** [comment]
meta property="og:description" content="IMDb, the world's most popular and authoritative source for movie, TV and celebrity content.">

**Comment by carvalho2707** [comment]
each page must have speficic keywords

**Comment by carvalho2707** [comment]
# About Us


# Index


# Match History


# Champ Rotation


# Server Status


# Summoner


# Summoner Chart


# Tables Comparison
